/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mac.gltf --transform
Author: Alejandro Ortiz (https://sketchfab.com/alejandroortizbecerra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-mac-cff5e2a310664beda981b80d4bbcf2b0
Title: LowPoly Mac
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert9SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert10SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert11SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.lambert8SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
